### ISSUE TITLE
jQuery missing when installing with yarn and using with React

### ISSUE THREAD

**Issue by ailinrb** [freegroup/draw2d#37]
Hi,

when I try to use draw2d inside my React application after installing it via yarn add, it complains that jQuery is missing at the moment i run application.

Steps to reproduce:

1. yarn add jquery
2. yarn add draw2d
3. yarn add jquery-ui

Create component with the following code:

```jsx
import React, { Component } from "react";
import draw2d from "draw2d";

class Canvas extends Component {
  
  componentDidMount() {
    this.renderCanvas();
  }

  renderCanvas() {
    const canvas = new draw2d.canvas(this.idCanvas);
    canvas.installEditPolicy(
      new draw2d.policy.connection.DragConnectionCreatePolicy({
        createConnection: function() {
          let c = new draw2d.Connection();
          c.setOutlineColor("#00A8F0");
          c.setOutlineStroke(1);
          c.setRadius(5);
          c.setStroke(3);
          c.setRouter(
            new draw2d.layout.connection.ManhattanBridgedConnectionRouter()
          );
          return c;
        }
      })
    );
  }
  render() {
    return (
      <div>
        <div id={this.idCanvas} style={{ height: 1500, width: 1500 }}></div>
      </div>
    );
  }
}
export default Canvas;

```

And when i tried to run the app, it throws a jQuery error:

![image](https://user-images.githubusercontent.com/25807728/60360592-a182d080-99a1-11e9-9c46-9a77be40a9ce.png)

**Comment by Demak** [comment]
Hello, I have the same problem with Vue.js app and I think it will happen without any framework since draw2d.js bundles "jQuery.fn.autoResize" and "jquery.contextmenu.js" which both expect jQuery.
Also jQueryUI, jquery.browser.js and draw2d itself are required by some functions to be present in global namespace.
Quick and dirty fix is to add them as <script> on base html page, but it is far from optimal. Please consider importing above mentioned dependencies from npm.

**Comment by polmonroig** [comment]
I am having the same problem :( @ailinrb , did you found a workaround?

**Comment by freegroup** [comment]
draw2d didn't work with require/import. you must include them in the global index.html
