### ISSUE TITLE
Connection-drop connects wrong

### ISSUE THREAD

**Issue by InannaInai** [freegroup/draw2d#45]
There is an issue with connectiondrop

[your example](http://www.draw2d.org/draw2d_touch/jsdoc_6/#!/example/connection_drop)

If you create more then one 'BetweenFigure' and drop it in the right connection, than more often than not the connection will be connected wrong.
The connection connects the input port with an input port and an output port with an output port.

The same happens when the connection sting is smaller than the object of the BetweenFigure.

I'm not sure where to fix this. Please help :)

**Comment by Demak** [comment]
Hi, I had a similar problem with connections, the reason why this happens is because connection source and target are unrelated to input and output ports. Sometimes input port is a connection source and output port is target, and sometimes output is source and input is a target depending on which port user has clicked first. That example assumes that old connection source is an output port, so when you drop a figure on an initial connection it connects start figure's output port to new figure's input, but then it creates a new connection using new figure's output port as target and old end figure input as source. Thus a new connection has a reversed direction and when you drop a new figure onto it, wrong ports are connected.
To fix that, the quickest way is to switch CommandConnect params in onDrop function inside BetweenFigure.js. This will make new connection to be directed in the same way as old connection:
```cmd = new draw2d.command.CommandConnect(this.getOutputPort(0), oldTarget);```
instead of
```cmd = new draw2d.command.CommandConnect(oldTarget,this.getOutputPort(0));```
But to be sure that such situation won't happen again, since user can create a connection manually with wrong direction, you need to check which of connections port is input or output and assign accordingly:
```javascript
onDrop:function(dropTarget, x, y, shiftKey, ctrlKey)
{
    // Activate a "smart insert" If the user drop this figure on connection
    //
    if(dropTarget instanceof draw2d.Connection){
        let oldSource = dropTarget.getSource();
        let oldTarget = dropTarget.getTarget();
        let oldInput = oldSource instanceof draw2d.InputPort ? oldSource : oldTarget;
        let oldOutput = oldSource instanceof draw2d.OutputPort ? oldSource : oldTarget;

        let stack = this.getCanvas().getCommandStack();

        let cmd = new draw2d.command.CommandReconnect(dropTarget);
        /*command replaces source port in connection first and repaints figure, if source and target 
port will be same at that time it will cause error, clearing target port prevents that, but undoing and 
redoing this will still throw an error, either CommandReconnect or Connection.repaint need to be 
changed to fix that*/
        if(dropTarget.targetPort == oldOutput) dropTarget.targetPort = null;
        cmd.setNewPorts(oldOutput, this.getInputPort(0));
        stack.execute(cmd);

        let additionalConnection = createConnection();
        cmd = new draw2d.command.CommandConnect(oldInput, this.getOutputPort(0));
        cmd.setConnection(additionalConnection);
        stack.execute(cmd);

    }
}
```

**Comment by freegroup** [comment]
thanks for the bug and solution. I update the demo.

greetings - Andreas

**Comment by freegroup** [comment]
just twisted the source/target if the connection is drawn in reverse direction.
The problem can still exist if you are using "HybridPorts"

**Comment by InannaInai** [comment]
Thank you it worked!
