### ISSUE TITLE
Unable to instantiate figure

### ISSUE THREAD

**Issue by igihcksn** [freegroup/draw2d#61]
Hi, 
i have tried read the json document to show the shape in canvas, but i got a problem, btw i'm using reaact mybe anyone can help me to show me whats the problem?

log in browser:
![image](https://user-images.githubusercontent.com/22608147/67063766-161c8d80-f192-11e9-8ec9-e715785df806.png)

in my code:
![image](https://user-images.githubusercontent.com/22608147/67063792-364c4c80-f192-11e9-8824-780751cae146.png)

**Comment by markbailly72** [comment]
I have the same problem in an electron/nodejs application. If I require("draw2d") then I get the error that you mention, even when running one of the json examples. The code fails during the unmarshal function when it hits the eval(). I am able to fix this by including the draw2.js in my html file instead of requiring the module. Not sure why this is the case.

**Comment by igihcksn** [comment]
what you mean that remove require("draw2d") then add draw2d.js from node_module in file root html?
because i've try that but i get the same error, could you show your code to me about it?

**Comment by bettimms** [comment]
Same thing here with VueJS?

**Comment by freegroup** [comment]
draw2d must be **global**. Didn't work with import or require statements.
