### ISSUE TITLE
dynamic shapes of an UML diagram

### ISSUE THREAD

**Issue by Allam76** [freegroup/draw2d#80]
In the blog under release 4.0.3 there is a mention that there was work started on dynamic UML shapes. I can imagine that was a lot of work and later abandoned.

Is the work that was done still available somewhere? It could possibly be of great help to me.

Many thanks
Martin

**Comment by freegroup** [comment]
you are talking about the "Draw2d Touch" version. This lib discontinued. I no longer maintain the old version because there were simply too many restrictions. I was always forced to stay backwards compatible. I could not make radical changes. This repo is the successor.

anyhow...I implement a demo project to show how to implement dynamic shapes like a UML or DB modell on https://freegroup.github.io/draw2d/shape_db/index.html. Maybe this is a good starting point for you.

**Comment by Allam76** [comment]
That is exactly the one I'm already using. :smile: 
I'm fighting a bit on how to get nested raft shapes working but slowly getting there.
Many thanks.
